# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tigera-operator
sortOptions:
  order: fifo
patches:
- path: ds-priorityClass.yaml
  target:
    kind: Deployment
    name: tigera-operator
    namespace: tigera-operator
resources:
- tigera-operator.yaml
