# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "chart.labels" . | indent 4 }}
  name: {{ include "chart.name" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["watch", "list", "get"]
- apiGroups:
    - addons.cluster.x-k8s.io
    - bootstrap.cluster.x-k8s.io
    - clusterctl.cluster.x-k8s.io
    - controlplane.cluster.x-k8s.io
    - infrastructure.cluster.x-k8s.io
    - ipam.cluster.x-k8s.io
    - runtime.cluster.x-k8s.io
  resources: ["*"]
  verbs: ["watch", "list", "get"]
