# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ template "chart.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      serviceAccountName: {{ template "chart.name" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: webhook
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default $.Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - --webhook-cert-dir=/runtimehooks-certs/
        - --cni.calico.crs.defaults-namespace={{ .Release.Namespace }}
        - --cni.calico.helm-addon.defaults-namespace={{ .Release.Namespace }}
        - --cni.cilium.crs.defaults-namespace={{ .Release.Namespace }}
        - --cni.cilium.helm-addon.defaults-namespace={{ .Release.Namespace }}
        - --cni.cilium.helm-addon.default-values-template-configmap-name={{ .Values.hooks.cni.cilium.helmAddonStrategy.defaultValueTemplateConfigMap.name }}
        - --nfd.crs.defaults-namespace={{ .Release.Namespace }}
        - --nfd.helm-addon.defaults-namespace={{ .Release.Namespace }}
        - --nfd.helm-addon.default-values-template-configmap-name={{ .Values.hooks.nfd.helmAddonStrategy.defaultValueTemplateConfigMap.name }}
        {{- range $key, $value := .Values.extraArgs }}
        - --{{ $key }}={{ $value }}
        {{- end }}
{{- if .Values.env }}
{{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{- end }}
{{- end }}
        ports:
        - containerPort: 9443
          name: runtimehooks
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: probes
          protocol: TCP
        resources:
          {{ with .Values.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - mountPath: /runtimehooks-certs
          name: runtimehooks-cert
          readOnly: true
        livenessProbe:
          httpGet:
            port: probes
            scheme: HTTP
            path: /healthz
        readinessProbe:
          httpGet:
            port: probes
            scheme: HTTP
            path: /readyz
      securityContext:
        {{ with .Values.securityContext }}
        {{- toYaml . | nindent 8}}
        {{- end }}
      volumes:
      - name: runtimehooks-cert
        secret:
          defaultMode: 420
          secretName: {{ template "chart.name" . }}-runtimehooks-tls
