# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.CiliumCNI.defaultValueTemplatesConfigMaps.DockerCluster.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.CiliumCNI.defaultValueTemplatesConfigMaps.DockerCluster.name }}'
data:
  values.yaml: |-
    ipam:
      mode: kubernetes
{{- end -}}
