apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-ebs-kustomize
bases:
- aws-ebs-csi.yaml
patches:
- path: ./overlays/controller-nodeAffinity.yaml
  target:
    kind: Deployment
    name: ebs-csi-controller
    namespace: kube-system
- path: ./overlays/controller-nodeAffinity.yaml
  target:
    kind: Deployment
    name: snapshot-controller
    namespace: kube-system
- path: ./overlays/deployment-priorityClassName.yaml
  target:
    kind: Deployment
    name: snapshot-controller
    namespace: kube-system
- path: ./overlays/ds-tolerations.yaml
  target:
    kind: DaemonSet
    name: ebs-csi-node
    namespace: kube-system
