# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.CalicoCNI.defaultValueTemplatesConfigMaps.DockerCluster.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.CalicoCNI.defaultValueTemplatesConfigMaps.DockerCluster.name }}'
data:
  values.yaml: |-
    installation:
      cni:
        type: Calico
      calicoNetwork:
        ipPools:{{ printf "{{ range $cidr := .Cluster.spec.clusterNetwork.pods.cidrBlocks }}" }}
        - cidr: {{ printf "{{ $cidr }}" }}
          encapsulation: None
          natOutgoing: Enabled
          nodeSelector: all(){{ printf "{{ end }}" }}
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
{{- end -}}
