# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Unreleased fix from https://github.com/projectcalico/calico/commit/7f5db2347fc5f65ff74c67f7b588c8d9509f3dbe
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: NA
rules:
  # In addition to the above, the operator should have the ability to delete their own resources during uninstallation.
  - apiGroups:
      - operator.tigera.io
    resources:
      - installations
      - apiservers
    verbs:
      - delete
