apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterStaticIdentity
metadata:
  labels:
    cluster.x-k8s.io/provider: aws
  name: ${CLUSTER_NAME}
spec:
  allowedNamespaces:
    list:
      - default
  secretRef: aws-quick-start-creds
