apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/provider: aws
  name: aws-quick-start
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.128.0.0/12
  topology:
    class: aws-quick-start
    controlPlane:
      replicas: 1
    variables:
      - name: clusterConfig
        value:
          addons:
            cni:
              provider: calico
            csi:
              providers:
                - name: aws-ebs-sc
            nfd: {}
          aws: {}
    version: v1.27.5
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSClusterStaticIdentity
metadata:
  labels:
    cluster.x-k8s.io/provider: aws
  name: aws-quick-start
spec:
  allowedNamespaces:
    list:
      - default
  secretRef: aws-quick-start-creds
