apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/provider: aws
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: aws-quick-start
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
      - name: clusterConfig
        value:
          addons:
            cni:
              provider: Cilium
              strategy: HelmAddon
            cpi: {}
            csi:
              providers:
                - name: aws-ebs
            nfd:
              strategy: HelmAddon
          aws:
            region: us-west-2
          controlPlane:
            aws:
              ami:
                lookup:
                  baseOS: centos-7
                  format: capa-ami-{{.BaseOS}}-?{{.K8sVersion}}-*
                  org: "258751437250"
      - name: workerConfig
        value:
          aws:
            ami:
              lookup:
                baseOS: centos-7
                format: capa-ami-{{.BaseOS}}-?{{.K8sVersion}}-*
                org: "258751437250"
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
