apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/provider: docker
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: docker-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
      - name: clusterConfig
        value:
          addons:
            cni:
              provider: Cilium
              strategy: ClusterResourceSet
            nfd: {}
          docker: {}
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
