apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: nutanix
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    cluster.x-k8s.io/provider: infrastructure-nutanix
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - ${POD_CIDR:-192.168.0.0/16}
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - ${SERVICE_CIDR:-10.128.0.0/12}
  topology:
    class: nutanix-quick-start
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
      - name: clusterConfig
        value:
          addons:
            cni:
              provider: Calico
              strategy: ClusterResourceSet
          controlPlane:
            nutanix:
              machineDetails:
                additionalCategories:
                  - key: key1
                    value: value1
                  - key: key2
                    value: value2
                bootType: legacy
                cluster:
                  name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
                  type: name
                gpus:
                  - name: gpu1
                    type: name
                  - name: gpu2
                    type: name
                image:
                  name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
                  type: name
                memorySize: 4Gi
                project:
                  name: prj1
                  type: name
                subnet:
                  - name: ${NUTANIX_SUBNET_NAME}
                    type: name
                systemDiskSize: 40Gi
                vcpuSockets: 2
                vcpusPerSocket: 1
          nutanix:
            controlPlaneEndpoint:
              host: ${CONTROL_PLANE_ENDPOINT_IP}
              port: ${CONTROL_PLANE_ENDPOINT_PORT}
            failureDomains:
              - cluster:
                  name: PE1
                  type: name
                controlPlane: false
                name: fd1
                subnets:
                  - name: subnet1
                    type: name
            prismCentralEndpoint:
              additionalTrustBundle: trust-bundle-root-ca
              host: ${NUTANIX_ENDPOINT}
              insecure: ${NUTANIX_INSECURE}
              port: 9440
      - name: workerConfig
        value:
          nutanix:
            machineDetails:
              additionalCategories:
                - key: key1
                  value: value1
                - key: key2
                  value: value2
              bootType: legacy
              cluster:
                name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
                type: name
              gpus:
                - name: gpu1
                  type: name
                - name: gpu2
                  type: name
              image:
                name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
                type: name
              memorySize: 4Gi
              project:
                name: prj1
                type: name
              subnet:
                - name: ${NUTANIX_SUBNET_NAME}
                  type: name
              systemDiskSize: 40Gi
              vcpuSockets: 2
              vcpusPerSocket: 1
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
        - class: nutanix-quick-start-worker
          metadata: {}
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT}
