# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    capiext.labs.d2iq.io/cni: calico
  name: capi-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.128.0.0/12
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
      - name: etcdImageTag
        value: ""
      - name: coreDNSImageTag
        value: ""
      - name: podSecurityStandard
        value:
          audit: restricted
          enabled: true
          enforce: baseline
          warn: restricted
      - name: clusterConfig
        value: {}
    version: v1.27.5
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
