# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: goreleaser

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ fromJson(steps.versions.outputs.tools).golang }}
          check-latest: false
          cache: true

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ fromJson(steps.versions.outputs.tools).goreleaser }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
