# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: release-please-main

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3.7
        id: release-please
        with:
          release-type: go
          package-name: capi-runtime-extensions
          pull-request-title-pattern: "build${scope}: release${component} ${version}"
          changelog-notes-type: github

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Fetch all tags
        run: git fetch --force --tags

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Gather tool versions
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ fromJson(steps.versions.outputs.tools).golang }}
          check-latest: false
          cache: true

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ fromJson(steps.versions.outputs.tools).goreleaser }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ steps.release-please.outputs.release_created  }}
        name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          app_version: ${{ steps.release-please.outputs.tag_name  }}
          chart_version: ${{ steps.release-please.outputs.tag_name  }}
          target_dir: repo
